# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Simon Shillaker
description:      "Simon Shillaker's website"
url:              https://www.simonshillaker.com/
baseurl:          ""

author:
  name:           "Simon Shillaker"
  url:            https://www.simonshillaker.com/

github:
  user:           Shillaker

